### ISSUE TITLE
[1.12.2] Crash when using "fill" command

### ISSUE THREAD

**Issue by LiskoSlayer63** [abused/World-Border#1]
I tried the mod with my server and made a grand new save for it so I can test the `fill` command. Unfortunately it makes my server crash with `java.lang.IllegalAccessError`.

I uploaded the full crash log [here](https://pastebin.com/N7HYtB8N).

**Comment by Nitess** [comment]
Similar problem on my server
Latest forge 1.12.2 - 14.23.1.2566

`java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.ChunkProviderServer.field_73248_b from class com.wimbli.WorldBorder.task.ChunkUtil
	at com.wimbli.WorldBorder.task.ChunkUtil.unloadChunksIfNotNearSpawn(ChunkUtil.java:20)
	at com.wimbli.WorldBorder.task.WorldFillTask.onServerTick(WorldFillTask.java:365)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_841_WorldFillTask_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by abused** [comment]
Thanks for reporting, i didnt do much testing on 1.12 so did not expect this issue, ill have it fixed asap

**Comment by TheRedfoox** [comment]
Did you advance on the problem ? Because i encounter the same error for **trim** command

**Comment by abused** [comment]
Hmm, i cannot seem to reproduce this, testing as much as i can on my test server but it all seems to work fine, maybe some more info as to how you guys are attempting it? through console, player? did u change anything in the config?

**Comment by TheRedfoox** [comment]
I did not change any configuration of worldborder. I use the sponge but i tried without, but i still have this error ..
My server is empty as i execute the command.
The logs of the error :
![obdd2py](https://user-images.githubusercontent.com/19651327/34276201-a83187d8-e6a0-11e7-8657-975cae5c2bf3.png)
![zjihg1l](https://user-images.githubusercontent.com/19651327/34276207-ae6e1d64-e6a0-11e7-8c2f-50304781a6ca.png)

**Comment by abused** [comment]
Sill unable to reproduce, however i have attempted a fix for what the crash report had reported, if you guys could do me a favor and test it before i actually upload it on curse that'd be great!
https://github.com/abused/World-Border/releases/tag/1.0.6-beta

**Comment by TheRedfoox** [comment]
Your fix works perfectly ! The **trim** and **fill** is done without problems. Great job :)

I just noticed something in the log (patch 1.0.5 and 1.0.6) worldborder says that the **/wb** command is used by another mod (it was the only mod on the server). This does not prevent its operation but i wanted to make you go back

**Comment by abused** [comment]
All right perfect! As for that log it is because vanilla also has its own worldborder command so I'm seeing what I can do to disable that before I post a release

**Comment by LiskoSlayer63** [comment]
I tried the new 1.0.6 version, server didn't crash anymore and console says that it fills like it should. But when I did fullrender for Dynmap there's no new chunks.

**Comment by MegaPunchQ** [comment]
I can confirm that this fixed the issue with the crashing I also saw.  
While the fill command does work, I got this warning in the console.

> 31.12 22:49:57 [Server] Server thread/ERROR [worldborder]: All WorldBorder commands are being handled elsewhere:
31.12 22:49:57 [Server] Server thread/ERROR [worldborder]: * /wborder (from com.feed_the_beast.ftbu.ranks.CmdOverride)
31.12 22:49:57 [Server] Server thread/ERROR [worldborder]: * /wb (from com.feed_the_beast.ftbu.ranks.CmdOverride)
31.12 22:49:57 [Server] Server thread/ERROR [worldborder]: * /worldborder (from com.feed_the_beast.ftbu.ranks.CmdOverride)
31.12 22:49:57 [Server] Server thread/ERROR [worldborder]: It may be that another mod is attempting to provide world border functionality. Consider removing or disabling that mod to allow WorldBorder-Forge to work properly.

>

**Comment by smmmadden** [comment]
I get a similar failure and message stating that another mod may be using the same functionality.
This was after running >worldborder:wb world fill
I get the response to use wb fill confirm, so I issued: >worldborder:wb fill confirm
That fails with the below and crashes the server.  [Full startup log here](https://pastebin.com/1b7jGw2h):
[08:27:47] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.ChunkProviderServer.field_73248_b from class com.wimbli.WorldBorder.task.ChunkUtil
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:664) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:277) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.ChunkProviderServer.field_73248_b from class com.wimbli.WorldBorder.task.ChunkUtil
	at com.wimbli.WorldBorder.task.ChunkUtil.unloadChunksIfNotNearSpawn(ChunkUtil.java:20) ~[ChunkUtil.class:?]
	at com.wimbli.WorldBorder.task.WorldFillTask.onServerTick(WorldFillTask.java:365) ~[WorldFillTask.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_175_WorldFillTask_onServerTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652) ~[EventBus.class:?]
	... 5 more
[08:27:48] [Server thread/ERROR]: This crash report has been saved to: D:\Minecraft-Worlds\MC_PokemonRevival\.\crash-reports\crash-2018-01-07_08.27.48-server.txt
[08:27:48] [Server thread/INFO]: Stopping server
[08:27:48] [Server thread/INFO]: Saving players
[08:27:48] [Server thread/INFO]: Saving worlds
[08:27:48] [Server Shutdown Thread/INFO]: Stopping server

**Comment by Ashakiwi** [comment]
Minecraft: 1.12.2 - Forge: 14.23.5.2768 I've tried running fill in the console and from the game. Both crash with: 

Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.ChunkProviderServer.field_73248_b from class com.wimbli.WorldBorder.task.ChunkUtil
	at com.wimbli.WorldBorder.task.ChunkUtil.unloadChunksIfNotNearSpawn(ChunkUtil.java:20)
	at com.wimbli.WorldBorder.task.WorldFillTask.onServerTick(WorldFillTask.java:365)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_360_WorldFillTask_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by tonyvans** [comment]
> Sill unable to reproduce, however i have attempted a fix for what the crash report had reported, if you guys could do me a favor and test it before i actually upload it on curse that'd be great!
> https://github.com/abused/World-Border/releases/tag/1.0.6-beta

I can confirm this fixed it for me as well. Thank you and keep up the good work.
