### ISSUE TITLE
[1.10.2] Server crash after /wb fill confirm | World-Border-1.10.2-1.0.4

### ISSUE THREAD

**Issue by Marcel40625** [abused/World-Border#7]
Time: 3/10/18 9:18 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.world.gen.ChunkProviderServer.field_73248_b from class com.wimbli.WorldBorder.task.ChunkUtil
	at com.wimbli.WorldBorder.task.ChunkUtil.unloadChunksIfNotNearSpawn(ChunkUtil.java:20)
	at com.wimbli.WorldBorder.task.WorldFillTask.onServerTick(WorldFillTask.java:365)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_755_WorldFillTask_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

**Comment by izShelby** [comment]
Same problem here. Seems like there's a problem with the 1.10.2 version.

**Comment by BuildingMini** [comment]
Also have this issue with the 1.12 version.
